import { ACCUWEATHER_CONTENT_STRUCT, ACCUWEATHER_GEO_STRUCT, ACCUWEATHER_STRUCT } from './structs/accuweather.ts'
import { FORECA_CONTENT_STRUCT, FORECA_GEO_STRUCT, FORECA_STRUCT } from './structs/foreca.ts'
import { SIMPLE_GEO_STRUCT, SIMPLE_STRUCT } from './structs/simple.ts'

export const STRUCTS = {
	ACCUWEATHER: {
		WEATHER: ACCUWEATHER_STRUCT,
		GEO: ACCUWEATHER_GEO_STRUCT,
		CONTENT: ACCUWEATHER_CONTENT_STRUCT,
	},
	FORECA: {
		WEATHER: FORECA_STRUCT,
		GEO: FORECA_GEO_STRUCT,
		CONTENT: FORECA_CONTENT_STRUCT,
	},
	SIMPLE: {
		WEATHER: SIMPLE_STRUCT,
		GEO: SIMPLE_GEO_STRUCT,
	},
}
